---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-middleware
  namespace: openclaw
spec:
  encryptedData:
    users: AgCSRvsIKcHur0E2TVqL2DfZ2xFiibTi0yadeNn0KmO5OzLu9mCKni0XjsovQlNW69U8++0nq+9+mmYv1N3gUgLtX8H9dyX+ECjD0giYm+BqZCNk1pTBJPuz/n52NXBzRPDOibnVptFVRtzslp5eO7SBG1ewyHvqLdLHQt9nqfrXSDRSNPUU2EXWzngTOvwzgX266Trb+5WzQNGkIaq1fuzK41L0TpB4HjfMXEJAg4+EQMA5pHbHuy0j9b6OIoiDETvfUS3gNYHgXNVJsGl+WAcmG0pE2GFdlVzt2HtHQL8oo2ZrKrwFOW7jZL0vh256bomd29KY4pKb9K/nr/K/ro8W6wPM8LYKzhB3KGNQB66lE+hZdgyLUpV+6Xinc2qJIu86JFtSCTnfxZB3njne8hIrp1A0PvQ28HSDmEfEyY3QeoD1mA6LNieS6paI2Rag/OjruZdHe39nPcTzkoU5jkYOjSbXMhjflSJd26ZiAyHDSuBPHNgqbSKFnXLU0QbDAewg0RituacQ7TN7g77FOxknjA3SapraLpYTPEZgjyjAltufipGLaNi5quydj6CtnP43GKRhk9rHVn+isvuc/hMQJQ2nvuCHvDEERnJhEjx/6rxINUK2tcGH6Ik+ynxK1sPPCOebk/LKHOLgKU12wZ5HHo2ytKWnE5AxMixeQpHrHdWBWvU1DZQy8Tkp5YbDqcnV3yuh7odGBMrhsvHkjNMXzKcIap2s8BRhSRqBiG1APdKNePMk3CChZGitMh7ZtYg=
  template:
    metadata:
      name: openclaw-middleware
      namespace: openclaw
