apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config
  namespace: openclaw
data:
  # "fallbacks": [
  #   "google/gemini-3.1-flash-lite-preview",
  #   "google/gemini-3.0-flash-lite",
  #   "google/gemini-2.5-flash-lite"
  # ]
  openclaw.json: |
    {
      "gateway": {
        "bind": "lan",
        "port": 18789,
        "auth": {
          "mode": "token",
          "token": "${OPENCLAW_GATEWAY_TOKEN}"
        },
        "controlUi": {
          "allowedOrigins": [
            "https://openclaw.vps.jmsola.dev"
          ]
        },
        "trustedProxies": [
          "10.0.0.0/8",
          "172.16.0.0/12",
          "192.168.0.0/16"
        ]
      },
      "hooks": {
        "enabled": true,
        "token": "${OPENCLAW_HOOK_TOKEN}",
        "path": "/hooks",
        "presets": ["gmail"],
      },
      "agents": {
        "defaults": {
          "userTimezone": "Europe/Madrid",
          "model": {
            "primary": "openrouter/qwen/qwen3.6-plus:free",
          }
        },
        "list": [
          {
            "id": "main",
            "identity": {
              "name": "Claw",
              "theme": "helpful assistant",
              "emoji": "🦞",
            }
          }
        ]
      },
      "channels": {
        "telegram": {
          "enabled": true,
          "ackReaction": "👀",
          "dmPolicy": "allowlist",
          "allowFrom": [568838898],
          "groupAllowFrom": [568838898],
          "groups": { "*": { "requireMention": true } }
        },
        "whatsapp": {
          "enabled": true,
          "ackReaction": {
            "emoji": "👀",
          },
          "dmPolicy": "allowlist",
          "allowFrom": ["${WHATSAPP_PHONE_NUMBER}"],
          "selfChatMode": true,
          "groupPolicy": "allowlist",
          "groupAllowFrom": ["${WHATSAPP_PHONE_NUMBER}"],
          "groups": { "*": { "requireMention": true } }
        }
      },
      "logging": {
        "level": "info"
      }
    }