---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw
  namespace: openclaw
spec:
  encryptedData:
    google.gemini.api.key: AgA74B5g8Ljlq8NBGPf6/F4JwnIHjfKOaV+YpCX26muaWzU2ndnw3jSHAl4yCDIfoEB44X0lK+DSNuS3dHLhT9W2vM5zWZBlL4TlG3+yWQpWEbH81Lx6TmXkMlpw8hlXHdUtDV0WBLmH6UoeNoxldha/tOQEzOCnBuDInBz0/0WXXouLmC77PBCj5gob4QwFv1NdtlWnQhMW1bhpPq08fK4YT+wVllidqZ3wcmlKyh+vfp1C+4h6naRE8pPPspwaHQ8dpt7ZAhbBnJ105OCZQDbRMrMPHUpNFrlBChtgbZ6St8f8FR72IErpiKEaDn40G6hWP9gGPOA9Lyzp2UGyxZNXDPAgm0c8gQWuSiV4k8CKfxG24+8hxbG8rWqrISW7nxTMUlbcE4W9Shta4pmRSeS2RTs2a5RiU9aDLIUssHcNhjOylZoXUL7+rs4eTfofxZnMqepe6D9Osh38aB36jJehsN7uDXEBDrCYeQ4cxji3Fj6mTHdT8cdG96qV61cOXNz3fQHTAHADNyT1XDicDxEywUczx3Hx4DvCJpBQdeEDAsWYOHsSLvFMckBu0lF+mfLdY2xyFjlwFHdUfNKu4Z2ccXELKNhwFx6I9MXjbbASrFH23ZPtCFcxxyMZ4BZgCPmTMYPjkl9KIAhxprbqL6OMilhIh5OpxOwCdX7h7HNx+HSMB24SdyFQ3oaVXICj6k+nkHp2DEno+5R2+keBuzpWH3EZc3+SH826o9LD0F4HevP/jBO8EIk=
  template:
    metadata:
      name: openclaw
      namespace: openclaw
