---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw
  namespace: openclaw
spec:
  encryptedData:
    gateway.token: AgATb3MN+MiC0JUg5MtNAsv8TqYH9PYq8gMA8aShbDD2c3sD7r4DmJkuUVDWCoe1FjQJf1CmNebTHXMgaEnJqjV4Yz+P1rnS34suVbzFgS9AgNgqbEYuv6n0EiCKBLXXyVDsxD8jNhE+aP4kMZ0WQRHrGUL3hSyjapKDOgwTxGlk/6pfnM3E+9rq2j23t0BJSAXCsFK2nZOd910z0gSaqbMCf7Z1iBxsS4f6IbXS+jJfwy6fQvpSXaA6AVErMB/4/lKVLkDLLmBcUxH3QOzSY1ZtYA+5niKHjwpXWoZEjApvfqwrGI+cCO8o3khK/YQVehArp5Cj1rH3qeFokqllpq3Fg0Wq7gX67uMrvkc7dcBKfNu585iveqOnJDVLYjwmRI2OibeENWrjqQRCFhY2XqWXYDNrtRURSiGYPCTiK7xIEMWjfhMFju7jI+2H9HaxDCj4R5J8wFAWZfKUBTBBzEJIeOMcsXk+k75EEP3TlxplSirUz+hfINXGq69uWHUIPkqvCu6JQyxGuYtSJS03lXtwoXeJm45zaQfLA2cAJHzWbZTvBJIcnzZYxdltPP4dwsjRAOQ3KdFA/xT0/DEJCe5DCUqiWdyZI3gpAbFxfXO/31cQM3weuvzZCoOrF3bGuOwWRM1bvUfTOseND06bWxa5uv3hTjs2A46Qm6eTfcVACfX9Tgn1AFevuWzrErnz6i2rFDmpAGLulPZ5P387K19Q7z7hM4OOAse6RhGJBdx4g8ZD7mOqI1J699eEW6i65Tc=
    google.gemini.api.key: AgAzC0N9xtuKcHCegu1WNKYhxgSgrEvPHclTiwoMOHQVeaTSFhHwcsEU9xGCiphaRqLaHkayGejxeAPcl19dQHyAI7KJFp7AV5PkayTrLlghue8Rd7qqUjB02ZMCdgM9IZOJhiNcfU+tvqPzO+EtJsf38iIxsBlLrEhH4y67dVUSehW5l8e4mNtXH/g0PGUklKlY4CyFWpnFqo2uhK8JHKchGBgkgGQysMRmWGzxPT41/NDNqsLiEoOsoF7uWNSIRR+T3PpF07oqXv+RCt2mnqnjI/JABjZX4gYlfEIdeG7Nd21CwN6xc5dbMz9q9ef08EGwfG6Tr5pyTfN3CkZwBgiMeCT2rdr8WxypFt7dC5m0cwZ+lPmr/q/y7NK+ins3N5eegiEcCZm/9FJqOjuGsU78NHuTwBTl/xkY8+7aZL16snGG1wHZIW9VakYIN681eW4kqoZLNn/cF9gGo2aIeaXrxwoNOzsvN7lHpEdO2IcskKfj/UA5S8IMLK3idNO7muX2C6/2/ebtook3g6qvrepFaE5H2aICel7E1g0AMzur+FDivSr7ZxpiZogqRxdltW4RjSney+c/reNpBd/XyvA/DThOhPrxSl1pZXw8+SUx8yqLaQOE0LTNYkeDZmtpPgJ03cccOMsRa/UGMDOv7zFv1SzM2QAiaLlGDi+77L60olRdMl8kSmuxpPV0fcDm1F9Zcrl+UrlM/fChhK8u+nj9zVkPrmOtSlZ9vNJGbJeWCyrvHqebD/o=
  template:
    metadata:
      name: openclaw
      namespace: openclaw
